# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarTrackingTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic 
use_frameworks!
     pod 'IQKeyboardManagerSwift' ,'~> 4.0.4'
     pod 'Alamofire', '~> 4.3'
     pod 'SwiftyJSON'#, '~> 3.1.4'
     pod 'EVReflection', '~> 4.1.0'
     pod 'Hue'
     pod 'MBProgressHUD'
     pod 'Toast-Swift', '~> 2.0.0'


end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
